# Imagen base con g++ y cmake
FROM debian:bookworm-slim

# Actualizar e instalar dependencias necesarias
RUN apt-get update && apt-get install -y \
    g++ \
    make \
    cmake \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Crear carpeta de trabajo
WORKDIR /app

# Copiar todo el proyecto al contenedor
COPY . .

# Descargar Crow
RUN git clone https://github.com/CrowCpp/crow.git /tmp/crow && \
    mkdir -p crow && \
    cp -r /tmp/crow/include/crow/* crow/

# Descargar JSON
RUN mkdir -p nlohmann && \
    curl -L https://github.com/nlohmann/json/releases/latest/download/json.hpp -o nlohmann/json.hpp


# Compilar el proyecto
RUN g++ -std=c++17 api.cpp -o api -Icrow -Inlohmann -lpthread

# Exponer el puerto del servidor Crow (puedes cambiarlo en tu código)
EXPOSE 8080

# Comando para ejecutar el servidor
CMD ["./api"]
